# 🛠️ Pandas: Miscellaneous but Essential Operations

In this section, we'll explore a variety of useful **Pandas operations** that don’t necessarily fall into a specific category but are incredibly handy in day-to-day data analysis tasks.

<div style="text-align: center;">
  <a href="https://colab.research.google.com/github/MinooSdpr/Machine-Learning-101/blob/main/Session%2005/Session%2005_1%20-%20Operations.ipynb">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" />
  </a>
  &nbsp;
  <a href="https://github.com/MinooSdpr/Machine-Learning-101/blob/main/Session%2005/Session%2005_1%20-%20Operations.ipynb">
    <img src="https://img.shields.io/badge/Open%20in-GitHub-24292e?logo=github&logoColor=white" alt="Open In GitHub" />
  </a>
</div>


---


## 🔍 Exploring Unique Values

Understanding the **distinct values** in a column is crucial for analysis.

### Get unique values in a column:

In [1]:
import pandas as pd

df = pd.DataFrame({
    'col1': [1, 2, 3, 4],
    'col2': [444, 555, 666, 444],
    'col3': ['abc', 'def', 'ghi', 'xyz']
})

df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [2]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

### Count of unique values:

In [3]:
df['col2'].nunique()

3

### Frequency of each value (value counts):

In [4]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

## 🗑️ Permanently Remove a Column

To **delete a column** from the DataFrame:

In [5]:
del df['col1']

In [6]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

## 📊 Sorting & Ordering the DataFrame

You can sort a DataFrame by column values:

> ℹ️ By default, `inplace=False`, meaning the original DataFrame remains unchanged unless specified otherwise.

In [7]:
df.sort_values(by='col2') #inplace=False by default

   col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

## 🕵️‍♂️ Detecting Missing or Null Values

To **check for null (missing) values**:

> ✅ This is useful for identifying data that may require cleaning.

In [8]:
df.isnull()

    col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

<div style="float:right;">
  <a href="https://github.com/MinooSdpr/Machine-Learning-101/blob/main/Session%2005/Session%2005_2%20-%20Pandas%20Exercise%201.ipynb"
     style="
       display:inline-block;
       padding:8px 20px;
       background-color:#414f6f;
       color:white;
       border-radius:12px;
       text-decoration:none;
       font-family:sans-serif;
       transition:background-color 0.3s ease;
     "
     onmouseover="this.style.backgroundColor='#2f3a52';"
     onmouseout="this.style.backgroundColor='#414f6f';">
    ▶️ Next
  </a>
</div>